/**
 * Shared constants for the JLMT Lab Bot
 * No magic numbers or strings
 */

export const CONSTANTS = {
  SESSION: {
    DEFAULT_TTL_MINUTES: 30,
    CLEANUP_INTERVAL_MS: 5 * 60 * 1000, // 5 minutes
    MAX_SESSIONS: 1000,
    DEFAULT_MAX_SESSIONS: 1000,
  },
  
  TELEGRAM: {
    MAX_MESSAGE_LENGTH: 4096,
    DEFAULT_RATE_LIMIT: 30,
    RATE_LIMIT_WINDOW_MS: 1000,
    POLL_TIMEOUT_MS: 30000,
    RECONNECT_DELAY_MS: 5000,
    ERROR_RETRY_DELAY_MS: 3000,
    CHUNK_DELAY_MS: 100,
  },
  
  GEMINI: {
    DEFAULT_TIMEOUT_MS: 30000,
    DEFAULT_MODEL: 'gemini-2.0-flash',
    MAX_OUTPUT_TOKENS: 4096,
    TEMPERATURE: 0.7,
    TOP_P: 0.95,
    TOP_K: 40,
  },
  
  RETRY: {
    DEFAULT_ATTEMPTS: 3,
    DEFAULT_BASE_DELAY_MS: 1000,
    MAX_DELAY_MS: 30000,
    EXPONENTIAL_BASE: 2,
  },
  
  BLOG: {
    MAX_TITLE_LENGTH: 200,
    MIN_TITLE_LENGTH: 5,
    MAX_DESCRIPTION_LENGTH: 500,
    MIN_DESCRIPTION_LENGTH: 10,
    MAX_CONTENT_LENGTH: 50000,
    MIN_CONTENT_LENGTH: 100,
    MAX_TAGS: 10,
    MIN_TAGS: 1,
    MAX_TAG_LENGTH: 50,
  },
  
  PAPERS: {
    DEFAULT_MAX_PAPERS_TO_SCAN: 10,
    DEFAULT_TOP_PAPERS_TO_SHOW: 3,
    MAX_PAPERS_PER_REQUEST: 50,
    RELEVANCE_THRESHOLD: 0.5,
  },
  
  NEWS: {
    DEFAULT_MAX_NEWS_ITEMS: 20,
    MIN_RELEVANCE_SCORE: 1,
    RSS_TIMEOUT_MS: 15000,
    MAX_RSS_RETRIES: 2,
  },
  
  GIT: {
    DEFAULT_COMMIT_MESSAGE_PREFIX: 'blog:',
    MAX_COMMIT_MESSAGE_LENGTH: 1000,
  },
  
  RATE_LIMITER: {
    DEFAULT_CAPACITY: 30,
    DEFAULT_REFILL_RATE: 30,
    DEFAULT_REFILL_INTERVAL_MS: 1000,
  },
  
  CIRCUIT_BREAKER: {
    DEFAULT_FAILURE_THRESHOLD: 5,
    DEFAULT_RESET_TIMEOUT_MS: 60000,
    DEFAULT_HALF_OPEN_MAX_CALLS: 3,
  },
  
  VALIDATION: {
    MAX_COMMENT_LENGTH: 2000,
    MAX_FILE_PATH_LENGTH: 500,
    MAX_EDIT_INSTRUCTION_LENGTH: 500,
  },
} as const;

// Freeze to prevent accidental modifications
Object.freeze(CONSTANTS);
Object.freeze(CONSTANTS.SESSION);
Object.freeze(CONSTANTS.TELEGRAM);
Object.freeze(CONSTANTS.GEMINI);
Object.freeze(CONSTANTS.RETRY);
Object.freeze(CONSTANTS.BLOG);
Object.freeze(CONSTANTS.PAPERS);
Object.freeze(CONSTANTS.NEWS);
Object.freeze(CONSTANTS.GIT);
Object.freeze(CONSTANTS.RATE_LIMITER);
Object.freeze(CONSTANTS.CIRCUIT_BREAKER);
Object.freeze(CONSTANTS.VALIDATION);

